version: '2'

services:
  laravel_php:
    container_name: laravel_php
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./docker:/repo/docker
      - ./docker/provision/config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/provision/config/etc/php.ini:/etc/php.ini
    ports:
      - 8089:80
    stdin_open: true
